const config = require('../settings')
const {cmd , commands} = require('../lib/command')
const fs = require('fs');
const os = require("os");
const { igdl } = require("ruhend-scraper");
const yts = require('yt-search');
const {runtime} = require('../lib/functions')
const axios = require('axios');
const cheerio = require('cheerio');
const { Buffer } = require("buffer");
const wiki = require('wikipedia');


cmd({
    pattern: "ringtone",
    alias: ["ringtones", "ring"],
    desc: "Get a random ringtone from the API.",
    react: "🎵",
    use: ".ring",
    category: "download",
    filename: __filename,
},
async (conn, mek, m, { from, reply, args }) => {
    try {
        const query = args.join(" ");
        if (!query) {
            return reply("Please provide a search query! Example: .ringtone Suna");
        }

        const { data } = await axios.get(`https://www.dark-yasiya-api.site/download/ringtone?text=${encodeURIComponent(query)}`);

        if (!data.status || !data.result || data.result.length === 0) {
            return reply("No ringtones found for your query. Please try a different keyword.");
        }

        const randomRingtone = data.result[Math.floor(Math.random() * data.result.length)];

        await conn.sendMessage(
            from,
            {
                audio: { url: randomRingtone.dl_link },
                mimetype: "audio/mpeg",
                fileName: `${randomRingtone.title}.mp3`,
            },
            { quoted: m }
        );
    } catch (error) {
        console.error("Error in ringtone command:", error);
        reply("Sorry, something went wrong while fetching the ringtone. Please try again later.");
    }
});

cmd({
    pattern: "thenuxai",
    alias: ["aiimg", "generateimg", "aiimage"],
    desc: "Generate AI Images using Stable Diffusion",
    category: "ai",
    use: ".aiimg",
    react: "🤖",
    filename: __filename
},
async (conn, mek, m, { from, q, reply }) => {
    try {
        // Check if prompt is provided
        if (!q) return reply(`
*🤖 MALAKA-MD IMG AI 🖼️*

Usage: .thenuxai <image description>
Example: .thenuxai Beautiful landscape with mountains

*Tips:*
- Be specific in your description
- Use descriptive words
- Mention style, color, mood
`);

        // React to show processing
        await m.react("🔄");

        // Construct API URL with the prompt
        const apiUrl = `https://api.davidcyriltech.my.id/diffusion?prompt=${encodeURIComponent(q)}`;

        // Fetch the image from the API
        const response = await axios({
            method: 'get',
            url: apiUrl,
            responseType: 'arraybuffer',
            timeout: 60000 // 60 seconds timeout
        });

        // Check if response is valid
        if (!response.data) {
            return reply("❌ Failed to generate image. No data received.");
        }

        // Send the generated image
        await conn.sendMessage(from, {
            image: response.data,
            caption: `*🤖 MALAKA-MD IMG AI 🖼️*

*📝 Prompt:* ${q}

*Generated by ThenuxAI*
*Model:* Stable Diffusion
`,
            quoted: mek
        });

        // React to successful image generation
        await m.react("✅");

    } catch (error) {
        console.error("ThenuxAI Image Generation Error:", error);
        
        // React to error
        await m.react("❌");

        // Detailed error handling
        if (error.response) {
            // The request was made and the server responded with a status code
            console.log(error.response.data);
            console.log(error.response.status);
            console.log(error.response.headers);

            if (error.response.status === 429) {
                return reply("⏳ Too many requests. Please try again later.");
            } else if (error.response.status === 500) {
                return reply("🚫 Server error. Unable to generate image.");
            } else {
                return reply(`❌ Error: ${error.response.status} - ${error.response.statusText}`);
            }
        } else if (error.request) {
            // The request was made but no response was received
            console.log(error.request);
            return reply("🌐 No response received from the server. Check your internet connection.");
        } else {
            // Something happened in setting up the request that triggered an Error
            console.log('Error', error.message);
            return reply(`❌ An unexpected error occurred: ${error.message}`);
        }
    }
});


//=====================================

cmd({
    pattern: "system",
    alias: ["status","botinfo"],
    desc: "Check up time , ram usage and more",
    category: "main",
    use: ".system",
    filename: __filename
},
async(conn, mek, m,{from, quoted, body, isCmd, command, args, q, isGroup, sender, senderNumber, botNumber2, botNumber, pushname, isMe, isOwner, groupMetadata, groupName, participants, groupAdmins, isBotAdmins, isAdmins, reply}) => {
try{
let status = `
───────────────────
*㋛ 𝙿𝙾𝚆𝙴𝚁𝙳 𝙱𝚈 𝙼𝙰𝙻𝙰𝙺𝙰-𝙼𝙳 Ｍ〽️*
───────────────────

┌────────────────
│❖ *Uptime:*  ${runtime(process.uptime())}
│❖ *Ram usage:* ${(process.memoryUsage().heapUsed / 1024 / 1024).toFixed(2)}MB / ${Math.round(require('os').totalmem / 1024 / 1024)}MB
│❖ *HostName:* ${os.hostname()}
│❖ *Owner:* 𝙼𝙰𝙻𝙰𝙺𝙰-𝙼𝙳
└────────────────

*㋛ 𝙿𝙾𝚆𝙴𝚁𝙳 𝙱𝚈 𝙼𝙰𝙻𝙰𝙺𝙰-𝙼𝙳 Ｍ〽️*  
`
return reply(`${status}`)

}catch(e){
console.log(e)
reply(`${e}`)

}
})

cmd({
    pattern: "ping",
    alias: ["speed","cyber_ping"],
    desc: "To Check bot's ping",
    category: "main",
    use: '.ping',
    filename: __filename
},
async(conn, mek, m,{from, l, quoted, body, isCmd, command, args, q, isGroup, sender, senderNumber, botNumber2, botNumber, pushname, isMe, isOwner, groupMetadata, groupName, participants, groupAdmins, isBotAdmins, isAdmins, reply}) => {
try{
const nima = require("@whiskeysockets/baileys")
var inital = new Date().getTime();
let ping = await conn.sendMessage(from , { text: '*_Pinging..._* ❗'  } )
var final = new Date().getTime();
await conn.sendMessage(from, { text : 'Ping..10%' , edit : ping.key })
await conn.sendMessage(from, { text : 'Ping..30%' , edit : ping.key })
await conn.sendMessage(from, { text : 'Ping..50%' , edit : ping.key })
await conn.sendMessage(from, { text : 'Ping..80%' , edit : ping.key })
await conn.sendMessage(from, { text : 'Ping..100%' , edit : ping.key })

return await conn.sendMessage(from, { text : '❗ *Pong ' + (final - inital) + ' Ms* ' , edit : ping.key })
} catch (e) {
reply('*Error !!*')
l(e)
}
})

const forwardcmd = {
  pattern: "forward",
  desc: "forward msgs",
  alias: ["fo"],
  category: "owner",
  use: ".forward2 < Jid address 1, Jid address 2, ...>",
  filename: __filename,
};
cmd(forwardcmd, async (client, message, args, context) => {
  const { from,quoted,body,isCmd,command,args: commandArgs,q,isGroup,sender,senderNumber,botNumber2,botNumber,pushname,isMe,isOwner,groupMetadata,groupName,participants,groupAdmins,isBotAdmins,isAdmins,
    reply,
  } = context;
  if (!isOwner) {
    return reply("*Owner Only ❌*");
  }
  if (!q || !message.quoted) {
    return reply("*Provide the message and JID(s) ❌*");
  }
  let jidList = q.split(",").map((jid) => jid.trim());
  if (jidList.length === 0) {
    return reply("*Provide at least one valid JID ❌*");
  }
  let forwardMessage = {
    key: message.quoted?.fakeObj?.key,
  };
  if (
    message.quoted?.documentWithCaptionMessage?.message?.documentMessage
  ) {
    const mimeType = message.quoted.documentWithCaptionMessage.message.documentMessage.mimetype;
    const mime = require("mime-types");
    const extension = mime.extension(mimeType);
    let fileName =
      message.quoted.documentWithCaptionMessage.message.documentMessage.fileName;
    message.quoted.documentWithCaptionMessage.message.documentMessage.fileName =
      fileName || `file.${extension}`;
  }
  forwardMessage.message = message.quoted;
  let forwardedTo = [];
  for (let jid of jidList) {
    try {
      await client.forwardMessage(jid, forwardMessage, false);
      forwardedTo.push(jid);
    } catch (error) {
      console.log("Failed to forward to " + jid + ":", error);
    }
  }
  if (forwardedTo.length > 0) {
    return reply(
      "*Message successfully forwarded to:*\n\n" + forwardedTo.join("\n")
    );
  } else {
    return reply("*Failed to forward to all provided JIDs ❌*");
  }
});
